TARGET = libpedsim.so
SOURCES = $(shell echo *.cpp)
OBJECTS = $(SOURCES:.cpp=.o)
CUDA_SOURCES = $(shell echo *.cu)
CUDA_OBJECTS = $(CUDA_SOURCES:.cu=.co)
CXXFLAGS = -fPIC -shared -lm -fopenmp -march=native
CUDA_NVCC_FLAGS = --compiler-options -fPIC,-shared -Xcompiler -fopenmp -Xcompiler -march=native

# Detect the architecture
UNAME_S := $(shell uname -m)
ifeq ($(UNAME_S),x86_64)
    CXXFLAGS += -D__x86_64__
    CXXFLAGS += -mavx -lm
else ifeq ($(UNAME_S),arm64)
    CC = clang
    CXXFLAGS += -D__arm__
endif

all: $(TARGET)

$(TARGET): $(OBJECTS) $(CUDA_OBJECTS)
	$(CXX) $(FLAGS) $(CXXFLAGS) $(DEBUGFLAGS) -o $(TARGET) $(OBJECTS) $(CUDA_OBJECTS)

%.co: %.cu
	nvcc $(CUDA_NVCC_FLAGS) $(DEBUGFLAGS) -c -o $@ $<


clean:
	-rm $(TARGET) $(OBJECTS) $(CUDA_OBJECTS)
